apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: lnd
  annotations:
    appgw.ingress.kubernetes.io/health-probe-path: "/health" # pour dire Ã  Application Gateway comment tester la route health
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"   # pour remplacer /lnd/ par /

spec:
  ingressClassName: azure-application-gateway   # pour communiquer avec ingressControleur azure
  rules:
  - host: api-test.local
    http:
      paths:
      - path: /lnd/
        pathType: Exact
        backend:
          service:
            name: api-service
            port:
              number: 8000    # port du service et pas du pod
