apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: lnd
  annotations:
    appgw.ingress.kubernetes.io/health-probe-path: "/health"

spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: api-test.local
    http:
      paths:
      - path: /lnd
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 8000    # port du service et pas du pod
