apiVersion: v1
kind: Secret
metadata:
  namespace: lnd
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
stringData:
  mysql-username: user
  mysql-password: password
  mysql-root-password: rootpassword

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: lnd
  name: mysql-configmap
data:
  database_url: mysql-service
  database-name: clients