# ------------- Contient tous les mots de passe pour ne pas les exposer ----------

apiVersion: v1
kind: Secret
metadata:
  namespace: lnd
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
stringData:
  mysql-username: user
  mysql-password: password
  mysql-root-password: rootpassword

---

# ------------ Contient toures les données non secret utilisées dans les autres fichiers yaml -------------
# ------------ Evite les répétition et facilite la maintenance ------------------

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: lnd
  name: mysql-configmap
data:
  database-url: mysql-service
  database-name: clients